version: '3'
services:
  # db:
  #   image: mysql:5.7.20
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  # smtp:
  #   image: schickling/mailcatcher
  #   ports:
  #     - "1080:1080"
  #     - "1025:1025"
  # redis:
  #   image: redis:latest
  #   ports: 
  #     - 6379:6379
  db:
    image: postgres
  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - db
  web:
    build: .
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # command: bash -c "touch /myapp/tmp/pids/server.pid && rm /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: ./bin/server
    volumes:
      - .:/myapp:cached
    ports:
      - 3000:3000
      - 3035:3035
    depends_on:
      - db
